LottoCalendarView UI 구현 #4
AllenSwiftClass/LottoDiary pull request #12
Opened 2022-12-05 08:58 UTC by seunghyunCheon

## 🔍 개요
#4 
Fscalendar를 이용한 **달력 컴포넌트**와 달력 아래에 **컬렉션 뷰**를 위치시킨 뷰 컨트롤러와 선택한 날짜에 대해 종류, 구입금액, 당첨금액을 입력해 **로또를 추가**할 수 있는 뷰 컨트롤러해서 총 2개를 작성했습니다. 
- LottoCalendarViewController
- AddLottoViewController
    
## 📝 작업사항

### 구현 내용

#### 1.  LottoCalendarViewController
- ScrollView
`ScrollView`를 화면 `frame`에 꽉차게 만든 후 제일 상단에 `lottoCalendar`를, 바로 아래에 `CollectionView`를 위치시킨 후 컬렉션 뷰에서 필터링된 데이터 수에 따라서 컬렉션 뷰의 높이를 변경시킬 수 있게 만들었습니다.이는 `bottom.equalToSuper()`를 통해 화면끝까지 스크롤이 된다면 끝에 고정될 수 있게 만들었습니다.   
    
- Diffable DataSource + Compositional Layout
기존의 `DataSource`는 데이터의 변경 사항에 대해 수동으로 관리하고 동기화 해야한다는 단점이 있습니다. 이를 `reloadData()`로 업데이트를 해줬는데 이는 UI가 자연스럽게 변경되지 않아 UX경험을 저하시킬 수 있습니다. `Diffable DataSource`에서는 `Hash Value`와 `Snapshot`개념을 이용하기 때문에 변경된 부분에 대해서만 업데이트를 하기에 자연스럽게 보인다고 하네요.       
이 PR에서 사용한 컬렉션뷰는 `Section`이 하나밖에 없기에 `date`하나만,` item`은 `Lotto.ID`를 통해서 고유한 값을 가질 수 있게 만들었습니다.    
그리고 Snapshot이 자주 변경되고 사용될 것을 고려해 typeAlias로 만들었습니다.
`typealias DataSource = UICollectionViewDiffableDataSource<Section, Lotto.ID>`   
`typealias SnapShot = NSDiffableDataSourceSnapshot<Section, Lotto.ID>`
   
- ExpandButton
LottoCalendar파일안에 주간에서 월간을 전환시킬 수 있는 ExpandButton이 있으며, ExpandButtonDelegate를 정의해, 제일 상단의 viewController에서 프로토콜을 상속하고 역할을 위임받을 수 있게 만들었습니다.   
이 ExpandButton은 원래 LottoCalendar의 헤더뷰에 추가를 하려했으나 view들이 중첩되어 이벤트가 의도대로 전달되지 않아 헤더뷰가 아닌 Calendar 내부에서 직접 autoLayout을 주었습니다.    

- 달력 Header 변경
Fscalendar 내부의 헤더에 대해 attributed된 String을 전달시키기 위해서는 캘린더가 로드된 후의 시점에 적용하는 방법밖에 찾지못해서 이를 적용했습니다. `changeHeaderTitle`라는 이름의 메서드를 정의했고 캘린더 frame에 변화가 있을때마다 업데이트 해야하기때문에 많은 부분에서 사용이 되었습니다.

- RxSwift 적용
핵심 데이터(Lottos)를 처음 fetch된 이후에 외부에서 데이터를 주입시켜줘야하고 지나간 행위에 대해서 구독할 수 있게 해야하기 때문에 BehaviorSubject를 감시자로 두었습니다. 그리고 filteredLottos변수를 통해 선택된 날짜로 필터링된 stream을 만들었습니다.   
이들은 UI를 Update하는 부분이나 데이터를 변경시키는 부분에 subscribe를 함으로써 비동기 데이터를 선언적으로 처리할 수 있게 만들었습니다.

#### 2.  LottoCalendarViewController

- UITextFieldDelegate (입력할때마다 , 를 붙여주는 델리게이트 사용)
`textField(_ textField: UITextField, shouldChangeCharactersIn range: NSRange, replacementString string: String) -> Bool` 는 숫자가 입력 혹은 지워질때마다 호출되는 델리게이트로 replacementString을 통해서 textField를 직접 변화시킵니다. 여기서 핵심은 델리게이트에서 return true를 줘서 변화시키는 것이 아닌 직접 텍스트필드에 접근해서 수정을 하는 것입니다. 그래서 textField의 내용이 전부 지워지는 시점만 아니라면 전부 false를 리턴하는 것을 볼 수 있습니다.

- shakeTextField
100억 이상의 구매금액이나 당첨금액을 입력하려고 할 때 제한을 주기 위해 애니메이션을 적용했습니다. completion 여러개가 중첩되어 콜백지옥의 형태를 띄고있는데 다른 의견 있으면 말해주세요!

## 📸 구현 영상

https://user-images.githubusercontent.com/70146658/205593192-d2b62a77-5e8d-42a2-9c0b-ec0240444757.mov

## 🧐 참고 사항
realm적용 및 QR에 따른 로또 데이터적용은 추후 데이터 구조설계가 완료되고 할 예정입니다!

2022-12-08 13:58 UTC, SunnnySong requested changes
Good@@@@

2022-12-08 13:58 UTC, SunnnySong commented on LottoDiary/LottoDiary/Sources/Present/Calendar/ViewController/LottoCalendarViewController.swift
> +        }
DataSource = UICollectionViewDiffableDataSource<Section, Lotto> 로 설정하고,
```suggestion
    func configureDataSource() {
            dataSource = DataSource(collectionView: lottosCollectionView) {
            (collectionView, indexPath, identifier) -> UICollectionViewCell? in
            
            guard let cell = collectionView.dequeueReusableCell(
                withReuseIdentifier: LottoCell.reuseIdentifier,
                for: indexPath) as? LottoCell
            else { fatalError("Could not create new cell") }
            
            cell.purchaseAmount.text = "\(identifier.purchaseAmount.formattedWithSeparator) 원"
            cell.winningAmount.text = "\(identifier.winningAmount.formattedWithSeparator) 원"
            cell.type = identifier.type
            return cell
        }
```
이런식으로 구현하면, id를 받아 데이터 중 id가 동일한 Lotto 객체를 만들 필요 없이 cell과 연결할 수 있을 것 같습니다!
(아니면, dataSource에 Lotto 대신 Lotto.ID를 넣은 이유가 있을까요?)

2022-12-08 13:58 UTC, SunnnySong commented on LottoDiary/LottoDiary/Sources/Present/Calendar/ViewController/LottoCalendarViewController.swift
> +    let scrollView = UIScrollView()
아래로 스크롤시, 정상상적으로 보이는데
<img width="342" alt="스크린샷 2022-12-08 오후 6 22 05" src="https://user-images.githubusercontent.com/85678496/206408079-09b243bd-2caf-4ad7-b64c-7d6b4fd5f967.png">

화면을 위로 스크롤하면, 화면의 윗부분이 흰색으로 보입니다. 색상을 회색으로 변경하면 더 좋을 것 같습니다. 
<img width="342" alt="스크린샷 2022-12-08 오후 6 23 23" src="https://user-images.githubusercontent.com/85678496/206408423-3ba612cb-2aba-474a-9736-9b27247ecc59.png">

2022-12-08 13:58 UTC, SunnnySong commented on LottoDiary/LottoDiary/Sources/Present/Calendar/ViewController/LottoCalendarViewController.swift
> +                return self.lottosCollectionView.dequeueConfiguredReusableSupplementary(
```suggestion
                return collectionView.dequeueConfiguredReusableSupplementary(
```
collectionView로 해당 lottosCollectionView를 받아오니 대체해도 될 것 같습니다.

2022-12-08 13:58 UTC, SunnnySong commented on LottoDiary/LottoDiary/Sources/Present/Calendar/ViewController/LottoCalenderViewController+DataSource.swift
> +        self.present(vc, animated: true)
새로운 로또를 추가를 누르면 나오는 화면이 내부 요소들에 비해 지나치게 크다는 생각이 아주 잠깐 들었습니다. 이걸 half sheet으로 바꾸면 어떨지 문득 생각이 들었습니다~

2022-12-08 13:58 UTC, SunnnySong commented on LottoDiary/LottoDiary/Sources/Present/Calendar/ViewController/AddLottoViewController.swift
> +        winningTextField.attributedPlaceholder = NSAttributedString(string: "당첨금액을 입력해주세요", attributes: [NSAttributedString.Key.foregroundColor : UIColor.designSystem(.gray63626B)!])
```suggestion
        let placeholer = NSAttributedString(string: "당첨금액을 입력해주세요", attributes: [.font : UIFont.gmarksans(weight: .medium, size: ._20), .foregroundColor : UIColor.designSystem(.gray63626B)!])
        winningTextField.attributedPlaceholder = placeholer
```
이런 식으로 폰트까지 지정하면 어떨까 생각해봤습니다. 그리고 placeholder을 똑같은 설정으로 2개를 해야 하니 더 편리하게 아래 사진처럼 customTextField를 만들어 보는 것이 어떨까 생각해봤습니당. 

![스크린샷 2022-12-08 오후 10 52 39](https://user-images.githubusercontent.com/85678496/206463451-557576c4-e89c-4b76-a0dc-73a30e39dc81.png)

2022-12-08 13:58 UTC, SunnnySong commented on LottoDiary/LottoDiary/Sources/Present/Calendar/Views/LottoCell.swift
> +    }()
UILabel로 동일한 설정을 갖고 있으니 customLabel로 만드는 것이 어떨까 생각이 들었습니다.

2022-12-09 05:59 UTC, seunghyunCheon commented on LottoDiary/LottoDiary/Sources/Present/Calendar/ViewController/LottoCalendarViewController.swift
> +        }
Lotto를 hashable한 값으로 사용한다면 내부 id프로퍼티의 효용성이 사라진다고 생각했기 때문에 ID를 넣어줘서 사용했습니다 !

2022-12-09 07:12 UTC, seunghyunCheon commented on LottoDiary/LottoDiary/Sources/Present/Calendar/ViewController/LottoCalendarViewController.swift
> +    let scrollView = UIScrollView()
피드백 감사합니다 👍

2022-12-09 12:48 UTC, SunnnySong commented on LottoDiary/LottoDiary/Sources/Present/Calendar/ViewController/LottoCalendarViewController.swift
> +        }
오오,,저도 이렇게 바꿔야겠습니다,,

2022-12-15 06:31 UTC, kimscastle approved these changes
LGTM

2022-12-15 15:55 UTC, SunnnySong approved these changes

2022-12-15 16:42 UTC, merged