✨로또번호 랜덤으로 뽑아주는 뷰 구현
AllenSwiftClass/LottoDiary pull request #17
Opened 2022-12-11 14:16 UTC by kimscastle

## 🔍 개요
#14 

## 📝 작업사항
- 랜덤으로 번호뽑기 버튼을 누르면 새로운 번호들이 나오는 뷰를 구현했습니다
- 기존에 당첨번호를 넣어야하는데 api url에 회차번호를 넣어야해서 이부분을 어떻게하면 자동으로 업데이트 시킬지 고민해봐야합니다

## 📸 스크린샷 또는 영상
https://user-images.githubusercontent.com/99013115/206908735-c62d0d9c-4ab4-4b0e-a9ae-243d22c38ad5.mov

## 🧐 참고 사항
- 저번에 써니가 방식에 대해 물어본거같아서 고민을 해봤는데 combine이나 rx를 써야겠다 생각하고 코드를 짜려다가 didset으로도 충분히 구현이 가능할거같아서 그렇게 구현을 해놨습니다

- viewcontroller에서 addsubview를 여러개를 사용하는게 좀 가독성이 떨어지는거같아서 extention에 addsubviews를 추가해놨습니다
```swift
extension UIView {
    /// 화면에 여러 View들을 추가합니다
    /// - Parameter views: 추가할 View들
    func addSubviews(_ views: UIView...) {
        views.forEach { view in
            addSubview(view)
        }
    }
}
```

- 사용방법은 아래와 같습니다
```swift
addSubviews(firstNumberBall, secondNumberBall, thirdNumberBall, fourthNumberBall, fifthNumberBall, sixthNumberBall, plusImage, bounusNumberBall)
```

2022-12-14 08:59 UTC, SunnnySong requested changes
Goooood!

2022-12-14 08:59 UTC, SunnnySong commented on LottoDiary/LottoDiary/Sources/Present/NumberDrawTap/Views/LottoBall.swift
> +    }
로또 볼 색깔이 딱 정해진 것이 아니라, 숫자 자릿수에 따라 달라지는 거라고 알고 있어!
0 - 9 : 노랑
10 - 19: 파랑
20 - 29: 빨강
30 - 39: 회색
40 - 45: 연두?초록?
보너스 번호: 번호 자릿수에 따라 색깔 달라짐.
번호에 따라 볼 색깔이 달라지면 좋을것 같아!

2022-12-14 08:59 UTC, SunnnySong commented on LottoDiary/LottoDiary/Sources/Utility/Extensions/Int+.swift
> +    static let lottoRange: Range<Int> = 1..<30
로또 숫자는 1 - 45까지라 수정하면 좋을거같아!

2022-12-14 08:59 UTC, SunnnySong commented on LottoDiary/LottoDiary/Sources/Present/NumberDrawTap/Views/LottoNumbersView.swift
> +    }
로또 숫자를 넣을 때, 작은수부터 정렬해서 넣으면 좋을거같아!

2022-12-14 08:59 UTC, SunnnySong commented on LottoDiary/LottoDiary/Sources/Present/NumberDrawTap/Views/LottoBall.swift
> +            return .designSystem(.mainYellow)!
그때 우리 말한것처럼 노란색 채도를 더 낮추면 좋을거같아!

2022-12-15 04:55 UTC, seunghyunCheon approved these changes
LGTM

2022-12-18 05:50 UTC, SunnnySong approved these changes

2022-12-18 09:50 UTC, merged