:memo: 코드리뷰설명을 위한 Test 커밋입니다
AllenSwiftClass/LottoDiary pull request #5
Opened 2022-11-30 12:12 UTC by kimscastle

## 🔍 개요
`# + 이슈번호`로 관련 이슈를 알려주세요.

## 📝 작업사항
- 작업 내용 및 변경사항

## 📸 스크린샷 또는 영상

<p>
  <img src="" width="300">
</p>

| 제목 | 제목 |
|-----|-----|
| <img src="" width="250"> | <img src="" width="250"> |

## 🧐 참고 사항

## 📄 Reference
[]()

2022-11-30 12:34 UTC, kimscastle reviewed
디자인시스템을 잘 사용해주세요

2022-11-30 12:34 UTC, kimscastle commented on LottoDiary/LottoDiary/Sources/Present/ViewController.swift
> +        v.font = .systemFont(ofSize: 15, weight: .bold)
```suggestion
        v.font = .gmarksans(weight: .bold, size: ._17)
```
디자인시스템이 존재하기때문에 디자인시스템을 이용하는게 좋아보입니다

2022-11-30 12:34 UTC, kimscastle commented on LottoDiary/LottoDiary/Sources/Present/ViewController.swift
> +        }
```suggestion
        
        view.addSubview(codeReviewLabel)
        codeReviewLabel.snp.makeConstraints { make in
            make.top.equalTo(testLabel.snp.bottom).offset(20)
            make.leading.trailing.equalToSuperview().inset(30)
            make.width.equalToSuperview()
            make.height.equalTo(50)
        }
```
보통 offset은 다른 객체와의 비교에 사용하교 inset은 eqaultoSuperview와 사용합니다

2022-11-30 17:52 UTC, SunnnySong reviewed
Good!

2022-11-30 17:52 UTC, SunnnySong commented on LottoDiary/LottoDiary/Sources/Present/ViewController.swift
> +        v.textColor = .red
```suggestion
        v.textColor = .green
```
빨간색보다 녹색이 더 눈이 편안해 보일 것 같습니다.

2022-11-30 17:54 UTC, SunnnySong requested changes
Goooood

2022-11-30 17:54 UTC, SunnnySong commented on LottoDiary/LottoDiary/Sources/Present/ViewController.swift
> +        }
```suggestion
        codeReviewLabel.snp.makeConstraints { make in
            make.top.equalTo(testLabel.snp.bottom).inset(20)
            make.leading.trailing.equalToSuperview().offset(30)
            make.width.equalToSuperview()
            make.height.equalTo(70)
        }
```
codeReviewLabel의 height는 50보다 70이 더 적당할 것 같습니다.

2022-12-01 00:01 UTC, kimscastle commented on LottoDiary/LottoDiary/Sources/Present/ViewController.swift
> +        }
굿이요

2022-12-01 01:15 UTC, seunghyunCheon requested changes
LGTM

2022-12-01 01:15 UTC, seunghyunCheon commented on LottoDiary/LottoDiary/Sources/Present/ViewController.swift
> +        v.font = .systemFont(ofSize: 15, weight: .bold)
```suggestion
        v.font = .systemFont(ofSize: 15, weight: ._15)
```
디자인 시스템을 이용하는게 좋아보입니다.

2022-12-01 01:15 UTC, seunghyunCheon commented on LottoDiary/LottoDiary/Sources/Present/ViewController.swift
> +            make.top.equalTo(testLabel.snp.bottom).inset(20)
inset은 equalToSuperView와, offset은 다른 객체와 비교하여 사용합니다.

2022-12-01 06:57 UTC, SunnnySong requested changes
Good

2022-12-01 06:57 UTC, SunnnySong commented on LottoDiary/LottoDiary/Sources/Present/ViewController.swift
> +        v.font = .systemFont(ofSize: 15, weight: .bold)
```suggestion
        v.font = .systemFont(ofSize: 17, weight: .bold)
```
글자 크기를 키우는게 좋을 것 같습니다.

2022-12-01 06:57 UTC, SunnnySong commented on LottoDiary/LottoDiary/Sources/Present/ViewController.swift
> +        }
```suggestion
        codeReviewLabel.snp.makeConstraints { make in
            make.top.equalTo(testLabel.snp.bottom).inset(20)
            make.leading.trailing.equalToSuperview().offset(30)
            make.width.equalToSuperview()
            make.height.equalTo(70)
        }
```
height를 키우는 것이 더 좋을 것 같습니다.

2022-12-01 07:19 UTC, kimscastle commented on LottoDiary/LottoDiary/Sources/Present/ViewController.swift
> +        v.font = .systemFont(ofSize: 15, weight: .bold)
넵

2022-12-01 07:19 UTC, kimscastle commented on LottoDiary/LottoDiary/Sources/Present/ViewController.swift
> +        v.font = .systemFont(ofSize: 15, weight: .bold)
넵

2022-12-01 07:19 UTC, kimscastle commented on LottoDiary/LottoDiary/Sources/Present/ViewController.swift
> +        }
굿

2022-12-01 07:20 UTC, seunghyunCheon approved these changes
approve

2022-12-01 07:26 UTC, SunnnySong approved these changes
approve

2022-12-01 07:27 UTC, merged